version: "2"
services:

    redis:
        image: "redis:alpine"
        hostname: redis
        ports:
          - "6379:6379"
          
    orthanctoolsjs:
        image: salimkanoun/orthanctoolsjs
        container_name: orthanctoolsjs
        ports: 
            - 80:4000
            - 443:4000
        restart: unless-stopped
        volumes: ["orthanctoolsjs:/OrthancToolsJs/data:Z"]
        environment:
            OrthancAddress: "http://orthanc"
            OrthancPort: "8042"
            OrthancUsername: "salim"
            OrthancPassword: "salim"
            DOMAIN_PROTOCOL: "http"
            DOMAIN_ADDRESS: "serverAddress"
    
    orthanc:
        image: osimis/orthanc:20.4.2
        container_name: orthanc
        restart: unless-stopped
        ports: ["8042:8042"]
        volumes: ["orthanc:/var/lib/orthanc/db:Z"]
        environment:
            ORTHANC__NAME: "OrthancToolsJS"
            ORTHANC__DICOM_SERVER_ENABLED: "true"
            ORTHANC__DICOM_MODALITIES_IN_DATABASE: "true"
            ORTHANC__ORTHANC_PEERS_IN_DATABASE: "true"
            DICOM_WEB_PLUGIN_ENABLED: "true"
            OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
            PYTHON_PLUGIN_ENABLED: "true"
            TRANSFERS_PLUGIN_ENABLED: "true"
            WORKLISTS_PLUGIN_ENABLED: "true"
            ORTHANC__REGISTERED_USERS: |
                {"salim": "salim"}
            ORTHANC__DICOM_WEB__ENABLE: "true"
            ORTHANC__DICOM_WEB__ROOT: "/dicom-web/"
            ORTHANC__DICOM_WEB__ENABLEWADO: "true"
            ORTHANC__DICOM_WEB__WADOROOT: "/wado"
            ORTHANC__DICOM_WEB__SSL: "true"
            ORTHANC__DICOM_WEB__STUDIESMETADATA: "MainDicomTags"
            ORTHANC__DICOM_WEB__SERIESMETADATA: "Full"

   

volumes:
        orthanc:
        orthanctoolsjs:
