# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ redis ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install FrontEnd
      run: npm install
      working-directory: FrontEnd
    - name: BuildFront
      run: npm run-script build
      working-directory: FrontEnd
    - name: build OHIF
      run: git clone https://github.com/OHIF/Viewers.git
      run : cd Viewers
      run: yarn install
      run: QUICK_BUILD=true PUBLIC_URL=/viewer/ yarn run build
      working-directory: ohif
    - name: copy FrontEnd build to BackEnd
      run : mv build ../BackEnd
      working-directory: FrontEnd
    - name : copy OHIF
      run : mv dist ../BackEnd/build/viewer/
      working-directory: /ohif/Viewers/platform/viewer
    - name: copy Stone Of Orthanc
      run: wget https://lsb.orthanc-server.com/stone-webviewer/1.0/wasm-binaries.zip
      run: mkdir /stone
      run: unzip wasm-binaries.zip -d /stone
      run : mv stone ../BackEnd/build/viewer-stone/
      working-directory: stone
    - name: create ZIP distribution
      run : zip -r OrthancToolsJS.zip .
      working-directory: BackEnd
    - name: Create Release
      if: github.event.pull_request.merged == true
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.pull_request.title }}
        release_name: Release ${{ github.event.pull_request.title }}
        draft: true
        prerelease: true
    - name: Upload Release Asset
      if: github.event.pull_request.merged == true
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./BackEnd/OrthancToolsJS.zip
        asset_name: OrthancToolsJS.zip
        asset_content_type: application/zip
    - uses: actions/upload-artifact@v1
      with:
        name: OrthancToolsJS
        path: BackEnd
    - name: Install dependencies
      run: npm install
      working-directory: BackEnd
    - name: Test BackEnd
      run: npm test
      working-directory: BackEnd
      env:
        CI: true

